### ISSUE TITLE
Cannot install on mac

### ISSUE THREAD

**Issue by meg-bit** [arnesmits/DEP#28]
Hello,

I have some big challenges to install and load DEP. I have tried everything and listed below. 

I used either `BiocManager::install('DEP', type = 'source', dependencies = TRUE)` or `BiocManager::install('DEP')`. The message is the following: 
```
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cran.r-project.org/


Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.2 (2021-11-01)

Installing package(s) 'DEP'

also installing the dependencies ‘ncdf4’, ‘mzR’, ‘MSnbase’


Warning message in .inet_warning(msg):
“installation of package ‘ncdf4’ had non-zero exit status”
Warning message in .inet_warning(msg):
“installation of package ‘mzR’ had non-zero exit status”
Warning message in .inet_warning(msg):
“installation of package ‘MSnbase’ had non-zero exit status”
Warning message in .inet_warning(msg):
“installation of package ‘DEP’ had non-zero exit status”
Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done
```
I am using macOS Monterey Version 12.2.1
I am using R in the Jupyter notebook in an Anaconda environment. I had exactly the same environment in Windows and used DEP successfully. 
I cannot install DEP using RStudio either in this macOS. 
I tried to install using devtools through github and got the same error. 
I installed Xcode and GCC and did not solve the problem. 
**I can use other R and Bioconductor packages with no problem.**

**Comment by gadepallivs** [comment]
Any update on this issue. I was able to install using the github install code. But , when I load the package I get the following error

``` r
> library("DEP")
Error: package or namespace load failed for ‘DEP’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/username/Library/R/x86_64/4.2/library/gmm/libs/gmm.so':
  dlopen(/Users/username/Library/R/x86_64/4.2/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Users/username/Library/R/x86_64/4.2/library/gmm/libs/gmm.so
  Reason: image not found
```

**Comment by jmvarberg** [comment]
@gadepallivs I recently ran into similar issue and the answer at this link resolved the problem and let me load and use DEP

https://stackoverflow.com/questions/63511986/error-package-or-namespace-load-failed-for-gmm-in-dyn-loadfile-dllpath-dl
