### ISSUE TITLE
Error: object 'cols' not found, when we have exactly 7 samples

### ISSUE THREAD

**Issue by ericloud** [arnesmits/DEP#5]
https://github.com/arnesmits/DEP/blob/4204bbca3041e7249e0f0d1b11bb658b7bf6836a/R/plot_functions_explore.R#L304

Hi DEP's authors,  

Have you a good reason to don't manage a design with exactly 7 samples (in `var`) ? Or it's a typo ?

Thanks for your work,
Eric.

**Comment by arnesmits** [comment]
Hi Eric,

Thanks for your merge request.

Best,
Arne

-------------------------------------------------------------------------
Arne Smits

Postdoctoral Fellow
Genome Biology Unit - Huber & Steinmetz Groups
European Molecular Biology Laboratory (EMBL)
Meyerhofstrasse 1, 69117 Heidelberg, Germany

Cellzome - a GSK company
Heidelberg, Germany

phone: +49 6221 387 8632
e-mail: arne.smits@embl.de
